"""add dashboard_users dashboard_mfa_secrets dashboard_mfa_sessions tables

Revision ID: 3158f0c0a62e
Revises: a1b2c3d4e5f7
Create Date: 2026-02-23 12:59:16.194822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3158f0c0a62e'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('union_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_users_email'), ['email'], unique=True)

    op.create_table('dashboard_mfa_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_user_id', sa.Integer(), nullable=False),
    sa.Column('totp_secret', sa.Text(), nullable=False),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('mfa_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_user_id'], ['dashboard_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_user_id')
    )
    op.create_table('dashboard_mfa_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('mfa_type', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_user_id'], ['dashboard_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_mfa_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_mfa_sessions_session_token'), ['session_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_mfa_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_mfa_sessions_session_token'))

    op.drop_table('dashboard_mfa_sessions')
    op.drop_table('dashboard_mfa_secrets')
    with op.batch_alter_table('dashboard_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_users_email'))

    op.drop_table('dashboard_users')
    # ### end Alembic commands ###
