"""Add lifestyle fields to user

Revision ID: 42327788a4a8
Revises: a1b2c3d4e5f6
Create Date: 2026-02-03 14:07:02.629479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42327788a4a8'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuff_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_by', sa.Integer(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipped_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_days_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exercise_minutes_per_session', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('food_frequency', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('financial_stress', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stress_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('loneliness', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sleep_quality', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sleep_quality')
        batch_op.drop_column('loneliness')
        batch_op.drop_column('stress_level')
        batch_op.drop_column('financial_stress')
        batch_op.drop_column('food_frequency')
        batch_op.drop_column('exercise_minutes_per_session')
        batch_op.drop_column('exercise_days_per_week')

    op.drop_table('device_tokens')
    op.drop_table('cuff_requests')
    # ### end Alembic commands ###
