"""add email_hash column

Revision ID: 5e9248584016
Revises: 05cc86f00899
Create Date: 2026-01-27 14:00:20.671549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9248584016'
down_revision = '05cc86f00899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email_hash'), ['email_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_hash'))
        batch_op.drop_column('email_hash')

    # ### end Alembic commands ###
