"""Add enrollment_source, phq2 fields

Revision ID: 9908081b18c4
Revises: c7d8e9f0a1b2
Create Date: 2026-02-09 13:33:39.728057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9908081b18c4'
down_revision = 'c7d8e9f0a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phq2_interest', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phq2_depressed', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phq2_depressed')
        batch_op.drop_column('phq2_interest')
        batch_op.drop_column('enrollment_source')

    # ### end Alembic commands ###
