"""add token revocation, email verification, rate limiting

Revision ID: b19d3f662c99
Revises: 5e9248584016
Create Date: 2026-01-30 14:39:59.999198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19d3f662c99'
down_revision = '5e9248584016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_entries_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_entries_key'), ['key'], unique=False)
        batch_op.create_index('ix_rate_limit_key_endpoint_ts', ['key', 'endpoint', 'timestamp'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))

    # Data migration: existing approved users should not be locked out
    op.execute('UPDATE users SET is_email_verified = TRUE WHERE is_approved = TRUE')
    op.execute('UPDATE users SET is_email_verified = FALSE WHERE is_email_verified IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_email_verified')

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))

    op.drop_table('revoked_tokens')
    op.drop_table('email_verifications')
    with op.batch_alter_table('rate_limit_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_key_endpoint_ts')
        batch_op.drop_index(batch_op.f('ix_rate_limit_entries_key'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_entries_endpoint'))

    op.drop_table('rate_limit_entries')
    # ### end Alembic commands ###
